server:
  port: 8800

spring:
  datasource:
    url: jdbc:mysql://rm-cn-20p364uib000j98o.rwlb.rds.aliyuncs.com:3306/chengma?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ppp8989#$%
    type: com.zaxxer.hikari.HikariDataSource

# MyBatis-Plus的全局配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.chengma.mapper: debug

active:
  name: test-1