spring:
  datasource:
    url: jdbc:mysql://rm-cn-20p364uib000j98o.rwlb.rds.aliyuncs.com:3306/chengma?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ppp8989#$%
    type: com.zaxxer.hikari.HikariDataSource